// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAQ7eI3PG-d3rY76-fpW_itPpWd-BZs4uo',
    appId: '1:312152897356:web:3878b3a30c71a4b11cc1e9',
    messagingSenderId: '312152897356',
    projectId: 'to-do-346d3',
    authDomain: 'to-do-346d3.firebaseapp.com',
    storageBucket: 'to-do-346d3.firebasestorage.app',
    measurementId: 'G-D251VBK5L9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAZemtQAxYHwZmy_2b-U30au_yDZ4XRkVs',
    appId: '1:312152897356:android:2049d133f6c937281cc1e9',
    messagingSenderId: '312152897356',
    projectId: 'to-do-346d3',
    storageBucket: 'to-do-346d3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDP5cWWSNYkBbSkPN-EB2Ro6eu5FxbQV9Q',
    appId: '1:312152897356:ios:8da67db7d735d1f21cc1e9',
    messagingSenderId: '312152897356',
    projectId: 'to-do-346d3',
    storageBucket: 'to-do-346d3.firebasestorage.app',
    iosBundleId: 'com.example.flutterToDoList',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDP5cWWSNYkBbSkPN-EB2Ro6eu5FxbQV9Q',
    appId: '1:312152897356:ios:8da67db7d735d1f21cc1e9',
    messagingSenderId: '312152897356',
    projectId: 'to-do-346d3',
    storageBucket: 'to-do-346d3.firebasestorage.app',
    iosBundleId: 'com.example.flutterToDoList',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAQ7eI3PG-d3rY76-fpW_itPpWd-BZs4uo',
    appId: '1:312152897356:web:803fd5aa41d3efd91cc1e9',
    messagingSenderId: '312152897356',
    projectId: 'to-do-346d3',
    authDomain: 'to-do-346d3.firebaseapp.com',
    storageBucket: 'to-do-346d3.firebasestorage.app',
    measurementId: 'G-R8F404CYQX',
  );

}